tap "homebrew/fuse"
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "paritytech/paritytech"
tap "caskroom/cask"
tap "neovim/neovim"
tap "ethereum/ethereum"
cask "java"
cask "osxfuse"
cask "xquartz"
brew "ack"
brew "antiword"
brew "apr-util"
brew "autoconf"
brew "automake"
brew "gdbm"
brew "xz"
brew "python3"
brew "awscli"
brew "bash"
brew "berkeley-db@4"
brew "binutils"
brew "boost"
brew "freetype"
brew "fontconfig"
brew "gettext"
brew "pcre"
brew "glib"
brew "pixman"
brew "cairo"
brew "git"
brew "carthage"
brew "choose-gui"
brew "coreutils"
brew "icu4c"
brew "nspr"
brew "spidermonkey"
brew "couchdb"
brew "cscope"
brew "diff-so-fancy"
brew "docker", link: false
brew "erlang"
brew "findutils", args: ["with-default-names"]
brew "fzf"
brew "mpfr"
brew "gawk"
brew "gdb"
brew "glide"
brew "global"
brew "gnu-indent", args: ["with-default-names"]
brew "gnu-sed", args: ["with-default-names"]
brew "gnu-tar", args: ["with-default-names"]
brew "gnu-which", args: ["with-default-names"]
brew "nettle"
brew "libusb"
brew "gnupg", link: false
brew "pkg-config"
brew "gobject-introspection"
brew "grep"
brew "htop"
brew "libtool"
brew "imagemagick"
brew "jemalloc"
brew "libevent"
brew "libplist"
brew "usbmuxd"
brew "libimobiledevice"
brew "libtermkey"
brew "libuv"
brew "libvterm"
brew "libxml2"
brew "libyaml"
brew "links"
brew "lynx"
brew "mas"
brew "miniupnpc"
brew "msgpack"
brew "unibilium"
brew "neovim", args: ["HEAD"]
brew "node"
brew "nvm"
brew "openvpn"
brew "p7zip"
brew "pam-u2f"
brew "pass"
brew "phantomjs"
brew "pngquant"
brew "poppler"
brew "pyenv"
brew "qt"
brew "reattach-to-user-namespace"
brew "ruby"
brew "s3cmd"
brew "sshfs", link: false
brew "subversion"
brew "tesseract"
brew "the_silver_searcher"
brew "tmux"
brew "trash"
brew "unixodbc"
brew "unrar"
brew "unrtf"
brew "utf8proc"
brew "watch"
brew "watchman"
brew "wdiff", args: ["with-gettext"]
brew "wget"
brew "yarn"
brew "zplug"
brew "zsh"
brew "zsh-completions"
brew "ethereum/ethereum/ethereum"
brew "ethereum/ethereum/solidity"
brew "paritytech/paritytech/parity"
cask "iterm2"
cask "macdown"
cask "qlmarkdown"
cask "smcfancontrol"
cask "vagrant"
cask "vagrant-manager"
cask "virtualbox"
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "The Unarchiver", id: 425424353
