#!/usr/bin/env bash

echo "Installing dotfiles..."
echo
dotfiles_dir=`pwd`
cd "$dotfile_dir"
git pull origin master
echo

function install {

  # ZSH
  ln -sf "$dotfiles_dir/.zshrc" ~/.zshrc

  # Vim
  ln -sf "$dotfiles_dir/.vim/.vimrc" ~/.vimrc
  ln -sf "$dotfiles_dir/.vim" ~/.vim
  if [ ! -d "~/.config/nvim" ]; then
    mkdir -p ~/.config/nvim
  fi

  ln -sf "$dotfiles_dir/.vim/.vimrc" ~/.config/nvim/init.vim
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  # Git
  ln -sf "$dotfiles_dir/.gitconfig" ~/.gitconfig
  ln -sf "$dotfiles_dir/.gitignore" ~/.gitignore

  # Editor config
  ln -sf "$dotfiles_dir/.editorconfig" ~/.editorconfig

  # Karabiner configuration
  ln -sf "$dotfiles_dir/karabiner" ~/.config

  # vi file manager (vifm)
  if [ ! -d "~/.vifm" ]; then
    mkdir -p ~/.vifm
  fi
  ln -sf "$dotfiles_dir/vifmrc" ~/.vifm

  ln -sf "$dotfiles_dir/.vim/coc-settings.json" ~/.config/nvim

  # Cursor Editor
  ln -sf "$dotfiles_dir/cursor/settings.json" "/Users/kim/Library/Application Support/Cursor/User"
  ln -sf "$dotfiles_dir/cursor/keybindings.json" "/Users/kim/Library/Application Support/Cursor/User"

  echo "Installation completed. Enjoy!"
}

if [ "$1" == "--force" -o "$1" == "-f" ]; then
  install
else
  read -p "This will overwrite the existing dotfiles. Are you sure? (y/n) " -n 1
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    install
  fi
fi

