#!/usr/bin/env bash

echo "Installing dotfiles..."
echo
dotfiles_dir=`pwd`
cd "$dotfile_dir"
git pull origin master
echo

function install {

  # ZSH
  ln -sf "$dotfiles_dir/.zshrc" ~/.zshrc

  # Tmux
  ln -sf "$dotfiles_dir/.tmux.conf" ~/.tmux.conf

  # Vim
  ln -sf "$dotfiles_dir/.vim/.vimrc" ~/.vimrc
  ln -sf "$dotfiles_dir/.vim" ~/.vim
  if [ ! -d "~/.config/nvim" ]; then
    mkdir -p ~/.config/nvim
  fi

  ln -sf "$dotfiles_dir/.vim/.vimrc" ~/.config/nvim/init.vim
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  # Git
  ln -sf "$dotfiles_dir/.gitconfig" ~/.gitconfig
  ln -sf "$dotfiles_dir/.gitignore" ~/.gitignore

  # Editor config
  ln -sf "$dotfiles_dir/.editorconfig" ~/.editorconfig

  # Tmuxinator autocomplete
  if [ ! -d "~/.bin" ]; then
    mkdir ~/.bin
  fi

  ln -sf "$dotfiles_dir/tmuxinator.zsh" ~/.bin/tmuxinator.zsh

  # Powerline patched fonts
  ./fonts/install.sh

  # Enable key repeat for OSX
  defaults write -g ApplePressAndHoldEnabled -bool false

  # Karabiner configuration
  ln -sf "$dotfiles_dir/karabiner" ~/.config

  echo "Installation completed. Enjoy!"
}

if [ "$1" == "--force" -o "$1" == "-f" ]; then
  install
else
  read -p "This will overwrite the existing dotfiles. Are you sure? (y/n) " -n 1
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    install
  fi
fi

